<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="3" failed="0" ignored="0" total="5" passed="2">
  <reporter-output>
    <line>
      <![CDATA[Driver is set]]>
    </line>
    <line>
      <![CDATA[Properties file is loaded]]>
    </line>
    <line>
      <![CDATA[Website opened]]>
    </line>
    <line>
      <![CDATA[login details filled properly]]>
    </line>
    <line>
      <![CDATA[Unable to Login]]>
    </line>
    <line>
      <![CDATA[browser closed after test case execution]]>
    </line>
  </reporter-output>
  <suite name="Default suite" duration-ms="103324" started-at="2021-01-24T04:19:19Z" finished-at="2021-01-24T04:21:02Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="103324" started-at="2021-01-24T04:19:19Z" finished-at="2021-01-24T04:21:02Z">
      <class name="testCases.RegisterTestCase">
        <test-method status="PASS" signature="setBrowser()[pri:0, instance:testCases.RegisterTestCase@239963d8]" name="setBrowser" is-config="true" duration-ms="9508" started-at="2021-01-24T04:19:10Z" finished-at="2021-01-24T04:19:19Z">
          <reporter-output>
            <line>
              <![CDATA[Driver is set]]>
            </line>
            <line>
              <![CDATA[Properties file is loaded]]>
            </line>
          </reporter-output>
        </test-method> <!-- setBrowser -->
        <test-method status="PASS" signature="OpenWebsite()[pri:0, instance:testCases.RegisterTestCase@239963d8]" name="OpenWebsite" is-config="true" duration-ms="908" started-at="2021-01-24T04:19:19Z" finished-at="2021-01-24T04:19:20Z">
          <reporter-output>
            <line>
              <![CDATA[Website opened]]>
            </line>
          </reporter-output>
        </test-method> <!-- OpenWebsite -->
        <test-method status="PASS" signature="RegisterAsIndividual(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:1, instance:testCases.RegisterTestCase@239963d8]" name="RegisterAsIndividual" duration-ms="56819" started-at="2021-01-24T04:19:21Z" data-provider="dp" finished-at="2021-01-24T04:20:17Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Individual User]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[tester]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[random]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[ruchid@123]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[Lotus@123]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[Lotus@123]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- RegisterAsIndividual -->
        <test-method status="SKIP" signature="RegisterAsIndianAcademic(java.util.Hashtable)[pri:2, instance:testCases.RegisterTestCase@239963d8]" name="RegisterAsIndianAcademic" duration-ms="0" started-at="2021-01-24T04:20:17Z" data-provider="dp" finished-at="2021-01-24T04:20:17Z">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[java.lang.NegativeArraySizeException]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: java.lang.NegativeArraySizeException
at org.testng.internal.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:49)
at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:131)
at org.testng.internal.Parameters.handleParameters(Parameters.java:706)
at org.testng.internal.ParameterHandler.handleParameters(ParameterHandler.java:49)
at org.testng.internal.ParameterHandler.createParameters(ParameterHandler.java:37)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:924)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.NegativeArraySizeException
at utilities.TestDataProvider.getData(TestDataProvider.java:58)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:74)
at org.testng.internal.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:45)
... 22 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- RegisterAsIndianAcademic -->
        <test-method status="SKIP" signature="RegisterAsStartUp(java.util.Hashtable)[pri:3, instance:testCases.RegisterTestCase@239963d8]" name="RegisterAsStartUp" duration-ms="0" started-at="2021-01-24T04:20:17Z" data-provider="dp" finished-at="2021-01-24T04:20:17Z">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[java.lang.NegativeArraySizeException]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: java.lang.NegativeArraySizeException
at org.testng.internal.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:49)
at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:131)
at org.testng.internal.Parameters.handleParameters(Parameters.java:706)
at org.testng.internal.ParameterHandler.handleParameters(ParameterHandler.java:49)
at org.testng.internal.ParameterHandler.createParameters(ParameterHandler.java:37)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:924)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.NegativeArraySizeException
at utilities.TestDataProvider.getData(TestDataProvider.java:58)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:74)
at org.testng.internal.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:45)
... 22 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- RegisterAsStartUp -->
        <test-method status="SKIP" signature="RegisterAsMSME(java.util.Hashtable)[pri:4, instance:testCases.RegisterTestCase@239963d8]" name="RegisterAsMSME" duration-ms="0" started-at="2021-01-24T04:20:17Z" data-provider="dp" finished-at="2021-01-24T04:20:17Z">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[java.lang.NegativeArraySizeException]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: java.lang.NegativeArraySizeException
at org.testng.internal.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:49)
at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:131)
at org.testng.internal.Parameters.handleParameters(Parameters.java:706)
at org.testng.internal.ParameterHandler.handleParameters(ParameterHandler.java:49)
at org.testng.internal.ParameterHandler.createParameters(ParameterHandler.java:37)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:924)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.NegativeArraySizeException
at utilities.TestDataProvider.getData(TestDataProvider.java:58)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:74)
at org.testng.internal.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:45)
... 22 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- RegisterAsMSME -->
        <test-method status="PASS" signature="Login()[pri:5, instance:testCases.RegisterTestCase@239963d8]" name="Login" duration-ms="44000" started-at="2021-01-24T04:20:17Z" depends-on-methods="testCases.RegisterTestCase.RegisterAsIndividual" finished-at="2021-01-24T04:21:01Z">
          <reporter-output>
            <line>
              <![CDATA[login details filled properly]]>
            </line>
            <line>
              <![CDATA[Unable to Login]]>
            </line>
          </reporter-output>
        </test-method> <!-- Login -->
        <test-method status="PASS" signature="CloseWebsite()[pri:0, instance:testCases.RegisterTestCase@239963d8]" name="CloseWebsite" is-config="true" duration-ms="930" started-at="2021-01-24T04:21:01Z" finished-at="2021-01-24T04:21:02Z">
          <reporter-output>
            <line>
              <![CDATA[browser closed after test case execution]]>
            </line>
          </reporter-output>
        </test-method> <!-- CloseWebsite -->
      </class> <!-- testCases.RegisterTestCase -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
